# Generated by Django 4.1.1 on 2022-11-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phone_book", "0006_alter_phonebook_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PhoneBook",
            new_name="Contact",
        ),
    ]
