# Generated by Django 4.1.3 on 2022-12-01 12:53

from django.db import migrations, models

import admin_users.models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_users", "0002_alter_adminuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="avatar",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=admin_users.models.get_user_avatar_path
            ),
        ),
    ]
